Add recommended event
CulmoneY/LinkUp pull request #78
Opened 2024-11-30 20:55 UTC by samyasnoun

Add Recommended Event Interactor and Associated Components

---

### Description
This pull request introduces the functionality for adding recommended events to a group's calendar. The following components have been added:
- **AddRecommendedEventDataAccessInterface**: Interface for retrieving the group from the data layer.
- **AddRecommendedEventInputBoundary**: Interface for the input boundary of the Add Recommended Event use case.
- **AddRecommendedEventOutputBoundary**: Interface for the output boundary, responsible for presenting the success of the event addition.
- **AddRecommendedEventInputData**: Input data containing the event and the group name to be added.
- **AddRecommendedEventOutputData**: Output data containing the event name once added.
- **AddRecommendedEventInteractor**: The interactor that implements the logic for adding the recommended event to the group calendar.

This functionality addresses the need for programmatically adding events suggested to a group, ensuring the group calendar is updated accordingly.

---

### Changes
- [x] Created the **AddRecommendedEventDataAccessInterface** for retrieving a group by its name.
- [x] Implemented the **AddRecommendedEventInputBoundary** to define the execution contract for adding a recommended event.
- [x] Added the **AddRecommendedEventOutputBoundary** to handle success responses.
- [x] Defined the **AddRecommendedEventInputData** class to hold the input for the interactor (event and group name).
- [x] Created the **AddRecommendedEventOutputData** class to encapsulate the event name as the output.
- [x] Developed the **AddRecommendedEventInteractor** to handle the logic of adding the recommended event to the group's calendar.

---

### Checklist
- [x] Code is clean and follows the project's coding standards
- [x] Documentation has been updated (if necessary)
- [x] All tests pass locally (if applicable)

---

### Additional Comments
This PR implements the full functionality for adding recommended events to a group's calendar based on the provided event data. The system ensures that the event is added only if the group exists and is successfully saved to the calendar. The output boundary provides a response containing the name of the event added.

2024-11-30 21:00 UTC, CulmoneY requested changes
This is not the intended logic for the usecase. All this usecase should do is add the event in the input data to the database

2024-11-30 21:29 UTC, CulmoneY submitted a review, later dismissed
This part looks good. Continue with the presenter, controller and DAO

2024-12-01 04:20 UTC, Lakssito requested changes
Please read my comments and make the required changes.

2024-12-01 04:20 UTC, Lakssito commented on src/daos/MongoDAO.java
> +        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
This Formatter is called a lot in other methods. Please refractor it and make this a instance variable.

2024-12-01 04:20 UTC, Lakssito commented on src/interface_adapter/AddRecommendedEvent/AddRecommendedEventPresenter.java
> +        this.viewManagerModel = viewManagerModel;
The View Manager Model is not used in this presenter. Please remove it.

2024-12-01 04:20 UTC, Lakssito commented on src/interface_adapter/AddRecommendedEvent/AddRecommendedEventState.java
> +    private String groupName;
GroupName is never called and can thus be removed. Please do so.

2024-12-01 04:31 UTC, Lakssito submitted a review, later dismissed
I approve this changes.

2024-12-01 04:38 UTC, Lakssito approved these changes
Everything looks good to me, I approve the changes.

2024-12-01 04:38 UTC, merged